### ISSUE TITLE
[iOS] opening/closing animation glitch

### ISSUE THREAD

**Issue by MaliciousFiles** [scorecardto/app#153]
A user reported something weird in the open/close animation on iOS, somewhat screenshotted below:

![IMG_0982](https://github.com/scorecardto/app/assets/57738870/c569c33b-0b77-49cc-99ce-b6f5730e39a4)

**Comment by blortle-dev** [comment]
Got a better screenshot:
![image](https://github.com/scorecardto/app/assets/144735570/b40a122a-c85f-4dac-b6d7-ca5af85ed307)

Other apps don't show this:
![image](https://github.com/scorecardto/app/assets/144735570/a666cada-ac35-4780-a1ab-d26af4840940)
