### ISSUE TITLE
Course Edit Sheet takes up entire display

### ISSUE THREAD

**Issue by adriancasares** [scorecardto/app#18]
The course edit sheet takes up a lot of height- multiple rows of icons colors, etc. 
![Screenshot 2024-02-02 at 3 27 35 PM](https://github.com/scorecardto/app/assets/67245238/624854cc-85e9-4436-b433-cf277722729c)

Todo:
- [ ] Icon categories 
- [ ] Decrease margins and sizes
- [ ] Move visibility downwards

**Comment by MaliciousFiles** [comment]
I think it's solved with 9642244, but feel free to reopen if it's still a problem.
