### ISSUE TITLE
Changing course color or icon incurs UI delay

### ISSUE THREAD

**Issue by adriancasares** [scorecardto/app#25]

**Comment by MaliciousFiles** [comment]
This happens due to the updating of `dataContext.courseSettings`. We can't just asynchronize the updating of that because then it allows users to incur large amounts of UI delay at once. Ideal solution is making it not have to update so much UI, but not sure how to do that.

**Comment by adriancasares** [comment]
No UI freezes anymore but changes still take about 500ms to propagate

**Comment by MaliciousFiles** [comment]
Looks fast enough in production.
